### ISSUE TITLE
how to inference?

### ISSUE THREAD

**Issue by a2394797795** [MCG-NJU/MOC-Detector#11]
stupid question

There is something wrong when I tried to evaluate on UCF101.  It says `RuntimeError: given chunk sizes don't sum up to the tensor's size (sum(chunk_sizes) == 135, but expected 40) ` at the end of inference. 

So should we  use  
 

> python3 det.py --task normal --K 7 --gpus 0,1,2,3,4,5,6,7 --batch_size 94 --master_batch 10 --num_workers 8 --rgb_model ../experiment/result_model/$PATH_TO_RGB_MODEL --flow_model ../experiment/result_model/$PATH_TO_FLOW_MODEL --inference_dir $INFERENCE_DIR --flip_test --ninput 5

and 
 

> python3 det.py --task normal --K 7 --gpus 0 --batch_size 1 --master_batch 1 --num_workers 2 --rgb_model ../experiment/result_model/dla34_K7_rgb_coco.pth --flow_model ../experiment/result_model/dla34_K7_flow_coco.pth --inference_dir /data0/liyixuan/speed_test/test --flip_test --ninput 5

sequently, or  just  the latter is needed?

**Comment by ArchiZX** [comment]
This error is caused by the remaining samples.(total % 135 == 40)
Please use the latter script after inference to solve it.
