### ISSUE TITLE
Training with ResNet

### ISSUE THREAD

**Issue by YuxuanHe04** [MCG-NJU/MOC-Detector#13]
Thanks for your excellent project. But I met a RuntimeError when I want to train the model with the 'resnet_18' as the backbone.
RuntimeError: Error(s) in loading state_dict for MOC_Net:
        size mismatch for branch.wh.0.bias: copying a param of torch.Size([256]) from checkpoint, where the shape is torch.Size([64]) in current model.
        size mismatch for branch.wh.0.weight: copying a param of torch.Size([256, 64, 3, 3]) from checkpoint, where the shape is torch.Size([64, 64, 3, 3]) in current model.
        size mismatch for branch.wh.2.weight: copying a param of torch.Size([2, 256, 1, 1]) from checkpoint, where the shape is torch.Size([2, 64, 1, 1]) in current model.
What should I do if I want to try the resnet backbone?

**Comment by ArchiZX** [comment]
Have you added `--arch resnet_18` and pulled the newest update version?

You can check your codes for this line:
https://github.com/MCG-NJU/MOC-Detector/blob/84593a1f03468dbbf4ec92d50042676dc2af8c5a/src/network/branch.py#L21

**Comment by YuxuanHe04** [comment]
> Have you added `--arch resnet_18` and pulled the newest update version?
> 
> You can check your codes for this line:
> https://github.com/MCG-NJU/MOC-Detector/blob/84593a1f03468dbbf4ec92d50042676dc2af8c5a/src/network/branch.py#L21

Thanks， it works after I update the project version.
