### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by nthhiep** [MCG-NJU/MOC-Detector#14]
Hi,
I got an error when running train.py.  There's no module "network/DCNv2/_ext".  The code implementation is missing. 

Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from MOC_utils.model import create_model, load_model, save_model, load_coco_pretrained_model, load_imagenet_pretrained_model
  File "D:/TOULON/MOC-Detector-master/src/MOC_utils/model.py", line 10, in <module>
    from network.moc_net import MOC_Net
  File "D:/TOULON/MOC-Detector-master/src/network/moc_net.py", line 7, in <module>
    from .dla import MOC_DLA
  File "D:/TOULON/MOC-Detector-master/src/network/dla.py", line 12, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "D:/TOULON/MOC-Detector-master/src/network/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "D:/TOULON/MOC-Detector-master/src/network/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
ModuleNotFoundError: No module named 'network.DCNv2._ext'

**Comment by ArchiZX** [comment]
try this
`cd ${MOC_ROOT}/src/network/DCNv2`
`bash make.sh`

**Comment by nthhiep** [comment]
Thanks for your reply. I have another error when running this bash file. The error is like this:
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead

This issue is also reported at https://github.com/xingyizhou/CenterNet/issues/559.
I follow the tips there. It is to replace  "from torch.utils.ffi import create_extension"
by
from pkg_resources import parse_version
if parse_version(torch.__version__) >= parse_version("1.0.0"):
    print("1111")
    from torch.utils.cpp_extension import BuildExtension as create_extension
else:
    print("2222")
    from torch.utils.ffi import create_extension


However, another error appears
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance.

Could you help me to fix this issue. Thanks.

**Comment by ArchiZX** [comment]
Please use PyTorch 0.4.1 with cuda9.0.

**Comment by nthhiep** [comment]
Thank you for your instruction. I cannot down up cuda version. So, I follow the solution proposed for CenterNet. 
1. Use cuda10 + pytorch 1.0
2. replace your DCNv2 folder by DCNv2 from  https://github.com/CharlesShang/DCNv2.git.
I found that the files of two DCNv2 folders and their content are different. But finally it seem to be ok.

**Comment by ArchiZX** [comment]
Never mind.
If you have any trouble, you can use branch `pytorch1.6.0`. But it may have some bugs.

**Comment by ArchieAlexArkhipov** [comment]
> Please use PyTorch 0.4.1 with cuda9.0.

I tried it, but it didn't change the "TypeError: dist must be a Distribution instance"

- pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
- cuda90                    1.0                  h6433d27_0    pytorch

**Comment by AiladReb** [comment]
> Thank you for your instruction. I cannot down up cuda version. So, I follow the solution proposed for CenterNet.
> 
> 1. Use cuda10 + pytorch 1.0
> 2. replace your DCNv2 folder by DCNv2 from  https://github.com/CharlesShang/DCNv2.git.
>    I found that the files of two DCNv2 folders and their content are different. But finally it seems to be ok.

Could you please share the environment file? I have the exact same issue. I'm still stuck with incompatibility versions
