### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by nthhiep** [MCG-NJU/MOC-Detector#17]

**Comment by nthhiep** [comment]
I have some questions related to flip_test mode.

1. In "normal_moc_det.py"/preprocess(), line 62, why do you convert the red channel of "flip_data". What does this mean? 
                     temp[:, :, 2] = 255 - temp[:, :, 2]

2. In "normal_moc_det.py"/process() function,  why don't you take the average of rgb_mov and rgb_mov_f (as well as flow_mov and flow_mov_f) like heatmap and mov output (lines 88,89, 100,101) ? 

3. rgb_output[1]['mov'], flow_output[1]['mov'] are computed for nothing? 

It's the same for stream_moc_det.py. I hope to get your explanation. Thank you for your reply.

**Comment by ArchiZX** [comment]
1. This is a specific channel for brox-flow rather than the red channel.

2. I tried, but this had no use.

3. Yes.

**Comment by nthhiep** [comment]
Thank you for your response. I have another question. In fact, the format of ground-truth tubes in "UCF101v2-GT.pkl" is as follows:

gttubes  = { 
         'parentfolder/videoname': {class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])      ]}

         ...

         'parentfolder/videoname': {class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])      ]}
}

Here, the datasets are single-object? Each video contain only one  action? And the class/identification of tubes is the class of videos (or the index of the parent folder's name)? 
In theory, your model is multi-object tracking, but it is trained by single-object data?

How about the general problem where there are multiple objects or multiple actions of different types in videos? For example: 
1) video with 2 people jumping -> need to identify
2) video with one jumping, one walking -> need to classify as normal

In this case, there exists only the class/identification for tubes, not for videos? And _gttubes[label] must be a dictionary of multiple elements, as follows?

gttubes  = { 
         'parentfolder/videoname': {  class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]]) ]

                                                      class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])]      ...}
         ...
         'parentfolder/videoname': {  class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]]) ]

                                                      class: [
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])
                  ...
                  array([[frame,x1,y1,x2,y2],...,[frame,x1,y1,x2,y2]])]      ...}
}

Many thanks,

**Comment by nthhiep** [comment]
Oh, flow-images are represented by HSV format, where the 0-channel means the direction and the 2-channel means the magnitude of the movement? So, when we flip images, we have to flip the direction of object movement. Thanks for the information, I forgot that.

**Comment by ArchiZX** [comment]
UCF101-24 is a multi-objects dataset but JHMDB-21 is a single-object dataset. (see our gifs)

According to my observation, both datasets are single-action as you declare.

I don't know the generalization performance for multi-actions. And indeed, the community demand for a newly large non-atomic multi-actions/multi-objects action detection dataset.

**Comment by nthhiep** [comment]
I checked in UCF101v2-GT.pkl and found that UCF101-24 is not only a single-action but also single-object dataset. In every video, only one object is annotated with box during the video (dispite the video may contains many objects). So, UCF101-24 is a single-object tracking dataset.

```
We have 
len(self._gttubes[v]) = 1 for every video v in  in self._gttubes
```



So, the dataset is single-object tracking

**Comment by ArchiZX** [comment]
`gttubes` : dictionary that contains the gt tubes for each video.
                    Gttubes are dictionaries that associate from each index of label, a list of tubes.
                    A tube is a numpy array with nframes rows and 5 columns, <frame number> <x1> <y1> <x2> <y2>.

`len(self._gttubes[v]) = 1` represents single-action rather than single-object.

And try to check `len(self._gttubes[v][class_index])`

For example, `len(pkl['gttubes']['Fencing/v_Fencing_g04_c03'][6])` ---> 4

**Comment by nthhiep** [comment]
Thank you very much for this example. I'm wrong. I drawn the boxes for Basketball/v_Basketball_g18_c02 and think that it's the same for other videos. Thanks again.

**Comment by xjsxujingsong** [comment]
Hi just found this issue. Can the proposed method support multi person multi action in one frame? such as in ava dataset?

**Comment by yixuanli98** [comment]
Yes, the Center Branch uses the focal loss and can handle multi-label classification.
