### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by nthhiep** [MCG-NJU/MOC-Detector#19]
Hi, I have some questions about the pretrained models and their state_dict 

1. In MOC_utils/model.py, 
- load_imagenet_pretrained_model() only loads weights to backbone subnet of MOC_net, while
- load_coco_pretrained_model() loads weights to both backbone and branch subnets.

The difference comes from the fact that coco_dla.pth, coco_resdcn18.pth, coco_resdcn101.pth are detector models, while resnet and dla34-ba72cf86.pth are classification models. Is this true? 

2. There is a difference in state dict between source and target models:
- model.py/create_model() creates models with the following keys
        branch.hm
        branch.mov
        branch.wh
-  model.py/load_coco_pretrained_model() modifies the keys as follows:
        backbone.reg
        backbone.hm
        branch.wh
Here, in load_coco_pretrained_model(), you renamed the state dict key of "hm" and "mov", from branch to backbone, in order to ignore them. At the same time, you tried to keep the key of wh unchanged, in order to reuse its weights.  Do I understand correctly? And why did you do that?

3. Similarly, in load_model(), you ignore branch.hm and branch.mov. Why?

4. Haven't you supported to load both rgb and flow models at the same time?

5. I'm confused between option load_model  and rgb_model, flow_model. 
Can we remove load_model  and replace it by rgb_model, flow_model? 
Whenever  rgb_model or flow_model options are not empty, we will load model's weights from the given paths. 

I'm sorry about these trivial questions and thanks for your reply.

**Comment by nthhiep** [comment]
I can guess the reason.
- "wh" output is computed from singleton frame feature like 2d detectors. So, we can profit weights of pretrained 2d detector
- conversly, "hm" and "mov" outputs are calculated from the stack of frame features. So, they must to be trained from scratch.

**Comment by ArchiZX** [comment]
1. Yes. (DLA pretrain including deformable and upsample layers)

2. Yes, your explanation is correct.

3. It's the ablation study for JHMDB.
https://github.com/MCG-NJU/MOC-Detector/blob/686b26e210894099010d16a2753bd505704c945f/src/MOC_utils/model.py#L38

4. https://github.com/MCG-NJU/MOC-Detector/blob/686b26e210894099010d16a2753bd505704c945f/src/detector/normal_moc_det.py#L25

5. `--load_model` used for recovery from specific epoch during training.
https://github.com/MCG-NJU/MOC-Detector/blob/686b26e210894099010d16a2753bd505704c945f/src/train.py#L64

**Comment by nthhiep** [comment]
Thank you for your feedback.
