### ISSUE TITLE
Decode output file from normal_inference.py to image

### ISSUE THREAD

**Issue by npduyduc** [MCG-NJU/MOC-Detector#2]
I am trying your normal interface
I want to see the output image for visualization, but the output of your file is pkl file and I don't know how to decode it? Please guide me.
I have read normal_inference.py and only a little understand that you put K images in to predict, but I can not convert your input back to the image, thereby better understanding how you predict.
Hope you can help me, thanks!
Sorry about my English.
Have a great day!

**Comment by ArchiZX** [comment]
Thanks for your attention!
In each pkl file, we save the corresponding video frame’s detection result rather than an image.(Line 110-113 normal_inference.py)
The detection result is a dictionary {class: tubelet}
The tubelet is numpy array as shape (num, 4*K + 1)
(num is the number of detected tubelet, ‘4*K + 1’ means K*(x1,x2,y1,y2) and tubelet score)
If you want to know more details, please see ‘function post_process’ in normal_moc_det.py

By the way, if you want to get the final video-level detection results, please run 'BuildTubes' first!

**Comment by ArchiZX** [comment]
Thanks for your attention!
In each pkl file, we save the corresponding video frame’s detection result rather than an image.(Line 110-113 normal_inference.py)
The detection result is a dictionary **{class: tubelet}**
The tubelet is numpy array as shape **(num, 4K + 1)**
(num is the number of detected tubelet, '4K + 1' means **K*(x1,x2,y1,y2)** and **tubelet score**)
If you want to know more details, please see '_function post_process_' in normal_moc_det.py

By the way, if you want to get the final video-level detection results, please run '_BuildTubes_' first!

**Comment by npduyduc** [comment]
Thanks for your response,
So, your pkl file structure is (24,4x29) in which we have 29 sets of (x1, y1, x2, y2) for 24 classes from 1 to 24 as long as all (x1, y1, x2, y2) exist, right?
I have tried and get many boxes with the same name on the output image, I don't know which ones is the result box and its accuracy.
Am I wrong? Can you explan for me what did I miss ?

**Comment by npduyduc** [comment]
Thanks for your response,
Can you explain to me how to train with custom dataset? I mean is how to label as same as ucf24 dataset, and how to arrange the input data for training?

**Comment by ArchiZX** [comment]
1. `brox-images` means BroxOpticalFlow. You can find it in opencv. We directly download the prefetched ucf24 brox-flow.
2. If you want to train with custom dataset, you should prepare the ground truth annotations similar to ucf or jhmdb.
3. Please change the num of classes, see https://github.com/MCG-NJU/MOC-Detector/blob/master/src/datasets/dataset/ucf101.py

**Comment by npduyduc** [comment]
I want to ask about UCF101v2-GT.pkl, I have read at base_dataset.py and understand its structure. However, I encountered this bug when trying to change it.
For example, I changed it to only the first 4 classes and each class have 1 test_videos.
```
File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/datasets/dataset/base_dataset.py", line 35, in __init__
    len assert (self._train_videos [self.split - 1]) + len (self._test_videos [self.split - 1]) == len (self._nframes)
AssertionError
```

After I hidden the assert line, I got this bug

```
Traceback (most recent call last):
  File "det.py", line 27, in <module>
    normal_inference (opt)
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/inference/normal_inference.py", line 94, in normal_inference
    dataset = Dataset (opt, 'test')
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/datasets/dataset/ucf101.py", line 16, in __init__
    super (UCF101, self) .__ init __ (opt, mode, self.ROOT_DATASET_PATH, pkl_filename)
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/datasets/dataset/base_dataset.py", line 55, in __init__
    vtubes = sum (self._gttubes [v] .values ​​(), [])
KeyError: 'B'
```

Can you show me how to create and save this edited file? Because when I saved with pickle.dump I saw that the code of the pkl file was changed. UCF101v2-GT.pkl original file must use encoding = 'iso-8859-1' to load, but the new file does not. 
I tried to find that ucf101 dataset only has train, test and class number, how can you create the remaining parameters?, like  <x1> <y1> <x2> <y2> in gttubes key.

**Comment by ArchiZX** [comment]
`train_videos` / `test_videos` is list with nsplits elements, each one containing the list of training/testing videos(`[[......], [......]]`).
You got `KeyError: 'B'` because keys in the first list should be int type(split number).

**Comment by npduyduc** [comment]
Yeah, I did it, thank you for spending time with me. The great project!
I now just need to know how to create brox-images then I can train with my data, it seems brox optical flow is not available in python. I think I will try it on cpp.
Thanks,

**Comment by ArchiZX** [comment]
It doesn't matter.
You can try RGB as input first.
Good luck!

**Comment by usamahjundia** [comment]
Hi, excuse me for bumping but i think my question is still well within the topic of this issue

You suggested to run build_tubes.py, and after reading the code, is my understanding correct:

build_tubes went through all the frame predictions (to put it in words, lets say at frame X, we have the predictions for frame X, X-1 up to X-K+1, and at frame X+1, we have predictions for frame X+1, X, X-1 up to X-K+2) and find the average for each frame (for example, the prediction of frame X from both [X, X-1 ... X-K+1] and [X+1, X, ... X-K+2] are collected together) for the final tube?

**Comment by ArchiZX** [comment]
Hi, you are right!
`build_tubes ` tends to link adjacent tubes together using overlapped regions(in your example `X-K+1, X-K ... X`).  It will generate a new tube contains frame `X+1, X ... X-K+1` and the link algorithm will go through the whole video to get video-level detection results.

**Comment by usamahjundia** [comment]
Thanks! If i were to use this in an online fashion (so no linking for the hwole vid), do i still need to do the nms you did inside the `build_tubes` function or i could just take the output of the `run` method of the MOCDetector Class?

**Comment by ArchiZX** [comment]
For online fashion you can use a small `--N`, but I believe NMS is helpful for visualization.
BTW, linking could be modified for online testing and I will try to make it (but can't guarantee).

**Comment by npduyduc** [comment]
I want to ask you about the model evaluation, I created following your output template in ../result/default from the label file, however, when running `python ACT.py --task frameAP --K 7 --th 0.5 - -inference_dir ./output/fight/ `I got this error:
```
inference_dirname is  ./output/fight/
threshold is  0.5
Traceback (most recent call last):
  File "ACT.py", line 383, in <module>
    frameAP(opt)
  File "ACT.py", line 108, in frameAP
    log_file = open(os.path.join(opt.root_dir, 'result', opt.exp_id), 'a+')
IsADirectoryError: [Errno 21] Is a directory: '/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/../result/default'
```
Seems to need a log file at opt.exp_id, I don't know what it is
But I can run frameAP_error, how are they different?
Can you explain to me where I was missing?

**Comment by ArchiZX** [comment]
Please remove the directory `../result/default`.
The `../result` directory only save frameAP/videoAP numerical results. By default the output will be written to '../result/default'.
