### ISSUE TITLE
Did not find movement strategies implemented in the code

### ISSUE THREAD

**Issue by alphadadajuju** [MCG-NJU/MOC-Detector#21]
Thank you for sharing such an amazing work and truely one of the clearest instructions in using the codes!

I read your paper that the Full Movement strategy gave the best results, where there is a "sequential"relationship between the movement and box branch (bounding boxes on current frames are regressed on centers predicted by the movement branch).  

However, I could not find relevant implementation in your code (e.g., box branch depending on movement branch).  Could you guide me where you implemented the movement strategy?
Thank you again!

**Comment by ArchiZX** [comment]
Training: from L127 to L132
https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/datasets/sample/sampler.py#L127

Inference: from L56 to L 72
https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/detector/decode.py#L56

**Comment by alphadadajuju** [comment]
I see. Thank you for your prmpt response!
