### ISSUE TITLE
performance variance on JHMDB

### ISSUE THREAD

**Issue by ShoufaChen** [MCG-NJU/MOC-Detector#25]
Hi,

Thanks very much for your awesome work.

May I ask do you meet a performance variance on JHMDB dataset?
In my case, I got a remarkable variance (about 2~4 mAP), especially in split 3.

**Comment by ArchiZX** [comment]
Do you mean that your model has the performance variance across three splits?

**Comment by ShoufaChen** [comment]
No. I mean that training on split_idx 3 multiple times, the mAP results vary remarkably.

**Comment by ArchiZX** [comment]
Sorry, I didn't train many times on JHMDB, but the performance gap is remarkable across three splits.

**Comment by ShoufaChen** [comment]
Thanks for your reply.  Would you mind sharing your results across three splits?

**Comment by ArchiZX** [comment]
rgb+flow
|split | F 0.5 | V 0.2 | V 0.5 | V 0.75 | V 0.5:0.95 |    
|s1       |    75.19    |    82.46    |    82.33    |    75.76     |      62.37       |
|s2       |    74.28    |    82.18    |    81.92    |    75.83     |      60.89      |
|s3       |    71.09    |    78.51    |    78.51    |    73.70      |      58.68     |

**Comment by ShoufaChen** [comment]
Thank you very much.
