### ISSUE TITLE
UCF101-GT_v2

### ISSUE THREAD

**Issue by jiaozizhao** [MCG-NJU/MOC-Detector#26]
Hi, Thanks for the great repo.
You gave the repo for downloading the corrected annotation here https://github.com/gurkirt/corrected-UCF101-Annots. But when I checked the repo, I can not find the file UCF101-GT_v2.pkl in the repo. There is a pkl file called pyannot.pkl. Is this one which you called UCF101-GT_v2.pkl here? So I need to convert the format of pyannot.pkl by myself or is there a specific link to directly download UCF101-GT_v2.pkl? Could you kindly provide it if there is? thanks a lot.

**Comment by ArchiZX** [comment]
I uploaded them to my Google Drive: https://drive.google.com/file/d/1aYsk_Mhe089M38FhFoDgK5DmL8ttMxk7/view?usp=sharing.

**Comment by jiaozizhao** [comment]
Great. Thanks a lot.
