### ISSUE TITLE
Confused about the `sample_cuboids` constraints

### ISSUE THREAD

**Issue by irvingzhang0512** [MCG-NJU/MOC-Detector#31]
Hi, thanks for your work! Helps a lot!

I have a question about the constrains in `sample_cuboids`

https://github.com/MCG-NJU/MOC-Detector/blob/686b26e210894099010d16a2753bd505704c945f/src/ACT_utils/ACT_aug.py#L128-L142

In the above codes, `ious` is the ious between the sampled cuboid and the gt tubes. And the constrains are:

1) `min_jaccard_overlap`: I thought it means **all ious shoud be larger than `min_jaccard_overlap`**, aka `ious.min() >= constraints['min_jaccard_overlap']`. However, in the above code `ious.max() >= constraints['min_jaccard_overlap']`, which means **at least one gt tube has iou > min_jaccard_overlap**

2) `max_jaccard_overlap`: I thought it means **all ious should be smaller than `max_jaccard_overlap`**, aka `ious.max() <= constraints['max_jaccard_overlap']`. However, in the above code `ious.min() >= constraints['max_jaccard_overlap']`, which means **all ious should be larger than `max_jaccard_overlap`**

Could you please explain these constrains?

**Comment by ArchiZX** [comment]
Hi, this part of codes are provided by ACT.
In my opinion, `min_jaccard_overlap` is a lower limit condition which means at least one GT got matched. On the other hand, `max_jaccard_overlap` restricts all GT should be taken into account.

**Comment by irvingzhang0512** [comment]
Got it, thanks for clarification.
