### ISSUE TITLE
Question about `down_ratio`

### ISSUE THREAD

**Issue by irvingzhang0512** [MCG-NJU/MOC-Detector#32]
Hi, thanks for your work! I'm trying to reproduce this model now.

I have a question about `down_ratio` in [Sampler](https://github.com/MCG-NJU/MOC-Detector/blob/686b26e210894099010d16a2753bd505704c945f/src/datasets/sample/sampler.py#L14)

Related codes are listed as follows

```python
        input_h = self._resize_height
        input_w = self._resize_width
        output_h = input_h // self.opt.down_ratio
        output_w = input_w // self.opt.down_ratio

        ....

        # resize the original img and it's GT bbox
        for ilabel in gt_bbox:
            for itube in range(len(gt_bbox[ilabel])):
                gt_bbox[ilabel][itube][:, 0] = gt_bbox[ilabel][itube][:, 0] / original_w * output_w
                gt_bbox[ilabel][itube][:, 1] = gt_bbox[ilabel][itube][:, 1] / original_h * output_h
                gt_bbox[ilabel][itube][:, 2] = gt_bbox[ilabel][itube][:, 2] / original_w * output_w
                gt_bbox[ilabel][itube][:, 3] = gt_bbox[ilabel][itube][:, 3] / original_h * output_h
        images = [cv2.resize(im, (input_w, input_h), interpolation=cv2.INTER_LINEAR) for im in images]
```

Why the resize ratios are different between gt tubes and raw images? I thought different ratios lead to wrong bboxes.
If `down_ratio == 4`, then after resize, the bboxes are much smaller in the resized image...

**Comment by ArchiZX** [comment]
Actually, they are the same...

**Comment by irvingzhang0512** [comment]
Sorry, I didn't catch you... Please correct me if I made some mistakes.

Images are resized from `original_h, original_w` to `input_w, input_h`.
If the tube gt bboxes are resized to the same ratio, then they should modified by the following code

```python
gt_bbox[ilabel][itube][:, 0] = gt_bbox[ilabel][itube][:, 0] / original_w * input_w
gt_bbox[ilabel][itube][:, 1] = gt_bbox[ilabel][itube][:, 1] / original_h * input_h
gt_bbox[ilabel][itube][:, 2] = gt_bbox[ilabel][itube][:, 2] / original_w * input_w
gt_bbox[ilabel][itube][:, 3] = gt_bbox[ilabel][itube][:, 3] / original_h * input_h
```

However, in the Sampler code, the gt tube bboxes are modified 

```python
gt_bbox[ilabel][itube][:, 0] = gt_bbox[ilabel][itube][:, 0] / original_w * output_w
gt_bbox[ilabel][itube][:, 1] = gt_bbox[ilabel][itube][:, 1] / original_h * output_h
gt_bbox[ilabel][itube][:, 2] = gt_bbox[ilabel][itube][:, 2] / original_w * output_w
gt_bbox[ilabel][itube][:, 3] = gt_bbox[ilabel][itube][:, 3] / original_h * output_h

# aka
gt_bbox[ilabel][itube][:, 0] = gt_bbox[ilabel][itube][:, 0] / original_w * input_w // self.opt.down_ratio
gt_bbox[ilabel][itube][:, 1] = gt_bbox[ilabel][itube][:, 1] / original_h * input_h // self.opt.down_ratio
gt_bbox[ilabel][itube][:, 2] = gt_bbox[ilabel][itube][:, 2] / original_w * input_w // self.opt.down_ratio
gt_bbox[ilabel][itube][:, 3] = gt_bbox[ilabel][itube][:, 3] / original_h * input_h // self.opt.down_ratio
```

**Comment by yixuanli98** [comment]
We calculate the loss on the final feature map whose shape is (output_h, output_w ). So we resize gt tubes into this shape. After inputing the raw images, they will have the same shape. In the inference process, we will resize the prediction tubes to the original shape(original_h, original_w) in [https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/detector/normal_moc_det.py#L130](url)

**Comment by yixuanli98** [comment]
We calculate the loss on the final feature map whose shape is (output_h, output_w ). So we resize gt tubes into this shape. After inputing the raw images, they will have the same shape. In the inference process, we will resize the prediction tubes to the original shape(original_h, original_w) in [normal_moc_det](https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/detector/normal_moc_det.py#L130)

**Comment by yixuanli98** [comment]
"box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="0eb28b1933aed6b27c2d24efe856ffe6c9c493d717fd079e478eeff4b3de5178" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">We calculate the loss on the final feature map whose shape is (output_h, output_w ). So we resize gt tubes into this shape. After inputing the raw images, they will have the same shape. In the inference process, we will resize the prediction tubes to the original shape(original_h, original_w) in&nbsp;normal_moc_det</task-lists></div><form class="js-comment-update" id="issuecomment-864897889-edit-form" action="https://github.com/MCG-NJU/MOC-Detector/issue_comments/864897889" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6OTE5NzM2NDMyIiwidCI6MTYyNDI2OTA3Mn0=--b73186ec83b049947236ff90d47a0fc8e0c5df56b4e91134a093010f257fc40c" data-url="/_render_node/MDU6SXNzdWU5MTk3MzY0MzI=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-06-21T09%3A51%3A08Z" data-last-modified="Mon, 21 Jun 2021 09:51:08 GMT" data-gid="MDU6SXNzdWU5MTk3MzY0MzI=" style="box-sizing: border-box;"></div></div></div></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline"></div></div></div>

**Comment by yixuanli98** [comment]
We calculate the loss on the final feature map whose shape is (output_h, output_w ). So we resize gt tubes into this shape. After inputing the raw images into the network, they will have the same resize ratios with gt tubes. In the inference process, we will resize the prediction tubes to the original shape(original_h, original_w) in [normal_moc_det](https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/detector/normal_moc_det.py#L130).

**Comment by irvingzhang0512** [comment]
Thanks for your reply, Got it now
