### ISSUE TITLE
train on the one gpu error

### ISSUE THREAD

**Issue by Deep-learning999** [MCG-NJU/MOC-Detector#35]
packages/torch/_utils.py", line 459, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 309, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

How to modify if you want to train on a single GPU

**Comment by Deep-learning999** [comment]
use one gpu CUDA out of memory

!CUDA_VISIBLE_DEVICES=0  python3 src/train.py --K 7 --exp_id Train_K7_rgb_coco \
--rgb_model /hy-nas/12/kinetics400_tiny/yolov5/experiment/result_model2 \
--batch_size 1 --master_batch 1 --lr 5e-4 --gpus 0 \
--num_workers 2 --num_epochs 12 --lr_step 6,8 --save_all

forward
    return dcn_v2_conv(
  File "/hy-nas/12/kinetics400_tiny/yolov5/src/network/DCNv2/dcn_v2.py", line 25, in forward
    output = _backend.dcn_v2_forward(
RuntimeError: CUDA out of memory. Tried to allocate 1.42 GiB (GPU 0; 15.75 GiB total capacity; 13.36 GiB already allocated; 868.44 MiB free; 13.62 GiB reserved in total by PyTorch)

**Comment by Deep-learning999** [comment]
use one gpu CUDA out of memory

!CUDA_VISIBLE_DEVICES=0 python3 src/train.py --K 7 --exp_id Train_K7_rgb_coco
--rgb_model ../experiment/result_model2
--batch_size 1 --master_batch 1 --lr 5e-4 --gpus 0
--num_workers 2 --num_epochs 12 --lr_step 6,8 --save_all

forward
return dcn_v2_conv(
File "/hy-nas/12/kinetics400_tiny/yolov5/src/network/DCNv2/dcn_v2.py", line 25, in forward
output = _backend.dcn_v2_forward(
RuntimeError: CUDA out of memory. Tried to allocate 1.42 GiB (GPU 0; 15.75 GiB total capacity; 13.36 GiB already allocated; 868.44 MiB free; 13.62 GiB reserved in total by PyTorch)

**Comment by Deep-learning999** [comment]
@ArchiZX

**Comment by Deep-learning999** [comment]
@wanglimin @vladostan @happyjin @ArchiZX

**Comment by Deep-learning999** [comment]
@Jintao Lin

**Comment by mmaGroupGitHub** [comment]
@Deep-learning999 were you able to compile DCN without any issues?

**Comment by Deep-learning999** [comment]
Can compile, evaluate and video test are all right, I just want to change to single GPU training@mmaGroupGitHub

**Comment by Deep-learning999** [comment]
Can your single GPU run

**Comment by ssk1997** [comment]
My opts:--batch_size 8 --master_batch 1 --lr 5e-4 --gpus 0--num_workers 0 --num_epochs 12 --lr_step 6,8. Don't use "--save all". I trained successfully with one 1080ti.

**Comment by Deep-learning999** [comment]
How long is this configuration training for a batch, my display is 15 hours, is there a way to speed up the training

**Comment by ssk1997** [comment]
Buy 4 RTX3090 ( ^ _ ^ )

**Comment by Deep-learning999** [comment]
Are there other parameter adjustment methods that can speed up the training process
