### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by aikuniverse** [MCG-NJU/MOC-Detector#39]
I run this command
![捕获](https://user-images.githubusercontent.com/67212491/127733051-a5d63a09-915c-41f1-8fdc-e2597687f377.JPG)
show
![捕获](https://user-images.githubusercontent.com/67212491/127733112-a7335b70-c70a-4670-8c3e-de90f6009115.JPG)

help me pls.

**Comment by yixuanli98** [comment]
What's your cuda version and your the cuda version of pytorch?

**Comment by yixuanli98** [comment]
What's your cuda version and your cuda version of pytorch?

**Comment by aikuniverse** [comment]
cuda9.0 and torch0.4.1 is not available for GPU 2080, so I have changed DCNv2 for pytorch1.x, cuda10.0 and torch1.0.1. but it didn't work well.
So what should I do if I want to train in 2080 ?

**Comment by yixuanli98** [comment]
Maybe you can change the pytorch to 1.6. Your cuda should be upgraded to 10.1, 10.2 or 9.2, which matches the cuda version of your pytorch. After you change the pytorch version, remember to build the DCNv2 again according to the [https://github.com/MCG-NJU/MOC-Detector/tree/pytorch1.6.0/src/network/DCNv2](https://github.com/MCG-NJU/MOC-Detector/tree/pytorch1.6.0/src/network/DCNv2)

**Comment by aikuniverse** [comment]
I have solved it, thks a lot.
