### ISSUE TITLE
GIF demo

### ISSUE THREAD

**Issue by reobroqn** [MCG-NJU/MOC-Detector#4]
Thanks for sharing your work!
I want to create a video with bounding box like your gif, but i don't know how, input a video and output frames or video with bounding box. Could you help me a little?
I have read your code, but seems like my level is not enough to understand all of its. :( 
Once again, thank you for your attention!

**Comment by ArchiZX** [comment]
Thanks for your attention!

If you want to visualize our detection results, please see this issue: https://github.com/MCG-NJU/MOC-Detector/issues/2.
If you just want to draw a bbox on video frame, you can use function `cv2.rectangle`  in `opencv-python`.

By the way, the above function just give you a single frame with bbox on it. You can use `imageio.mimsave` to create the gif results from stacked frames.

**Comment by ArchiZX** [comment]
Hi~
We upload visualization codes and I hope it can help you.
