### ISSUE TITLE
about branch construction

### ISSUE THREAD

**Issue by MichaelHL-ai** [MCG-NJU/MOC-Detector#40]
when you construct branch module,  ‘self.hm[-1].bias.data.fill_(-2.19)’  is used. What's the magic number meaning?

**Comment by yixuanli98** [comment]
This is the default hyper-parameter of focal loss, which is described in the chapter 4.1 of [Focal Loss for Dense Object Detection](https://arxiv.org/pdf/1708.02002.pdf)

**Comment by MichaelHL-ai** [comment]
I see, thx!
