### ISSUE TITLE
Some questions about spatial-temporal action detection

### ISSUE THREAD

**Issue by czhaneva** [MCG-NJU/MOC-Detector#41]
Thank you for your such awesome work !
I'm a new one to spatial-temporal action detection. I have some questions about spatial-temporal action detection. In my opinion, this task not only detects each person/object in the video (spatial), but also detects the temporal boundary  (start and end) of an action instance. In the paper, I found it focus on detecting the spatial boundary, So I'd like to know how to detect both spatial and temporal boundary of an action instance. Please forgive me if my understanding is wrong. Looking forward to your reply.

**Comment by yixuanli98** [comment]
We detect the temporal boundary in the linking process, which is described in the Chapter 3.4 of paper. For code implementation, you can refer to [https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/ACT_utils/ACT_build.py#L64](https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/ACT_utils/ACT_build.py#L64) .
