### ISSUE TITLE
Inference with flow model

### ISSUE THREAD

**Issue by WeiChihChern** [MCG-NJU/MOC-Detector#43]
Hi, thanks for sharing the great work.

I've a question regarding the flow model during training and inference.

I could not find an explanation/architecture illustrating the use of flow model. Is the flow model related to the term 'two-stream' that referenced in the paper?

Would you please explain a bit on how flow model is used for training and inference? Since I only found something related in the `Study on Movement Branch Design` Section.  Thanks a lot.

**Comment by yixuanli98** [comment]
Yes, the flow model is one of the two-stream model. The training and inference process of flow are the same with RGB. They are both the input of network. Maybe you can read the whole paper. You can refer to our Train.md and Evaluation.md for the command.

**Comment by yixuanli98** [comment]
This line [https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/datasets/sample/sampler.py#L24](https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/datasets/sample/sampler.py#L24) control the input of Flow and RGB. For Flow, the ninput is 5. For RGB, the ninput is 1.
