### ISSUE TITLE
Why ninput = 5 when input modality is flow?

### ISSUE THREAD

**Issue by r09921135** [MCG-NJU/MOC-Detector#46]
First of all, thank you for sharing this amazing work.
My question is about this line: 
https://github.com/MCG-NJU/MOC-Detector/blob/45c3fd0c5e4ca455e7e739f3ad80b2c91813df35/src/detector/stream_moc_det.py#L79
Why you have to stack 5 flow images and make the number of channels to be 15? 
Why can't we just treat the flow input the same as the RGB input?
Thank you!

**Comment by yixuanli98** [comment]
Following ACT[1], we stack 5 flow images as input. You could have a try on using single flow image as input to see if there's a decrease in accuracy.
[1] Action tubelet detector for spatio-temporal action localization.

**Comment by r09921135** [comment]
Thank you for the respond!
And I also notice that for the JHMDB dataset, there are a lot of missing samples in the flow images. 
How do you deal with this? Or you just calculate the flow images by yourselves?
