### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by happyjin** [MCG-NJU/MOC-Detector#5]
Thanks for your awesome project. I found an unimplementation bug in `det.py`.
`from inference.speed_test import speed_test_stream_inference` in the line 36. Hopefully you could add this missing file. Thanks in advance!

**Comment by ArchiZX** [comment]
Hi, thanks for your attention!
In general you will not meet this bug. Did you ever use `python3 det.py --task speed_test ......` in your bash script?
By the way, I will upload `speed_test.py` soon, which can estimate our online inference speed.

**Comment by happyjin** [comment]
Ohhh, sorry about the impropal title. I tried your `det.py` example and it works perfect. As you said, this is just a missing file.

**Comment by ArchiZX** [comment]
Never mind~
